# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vmr7t9dfM9tSgUL7nRfaXAYSjpoCEHQU
"""

def check_for_valid_str(text):
  text = text.lower()
  if (str.isdigit(text)):
    if (int(text) >= 0 and int(text) <=20):
      return int(text)
    else:
      print (text + " is out of range ")
      return -1
  elif (text in LookupGerman):
    return LookupGerman.index(text)
  elif (text in LookupFrench):
    return LookupFrench.index(text)
  elif (text in LookupEnglish):
    return LookupEnglish.index(text)

def print_data(data_list):
  for item in data_list:
    print(item)

LookupEnglish = ["zero","one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen","twenty"]
LookupGerman = ["null","eins", "zwei", "drei", "vier","funf","sechs", "acht", "neun", "zehn","elf","zwolf","dreizehn","vierzehn","funfzehn","sechzehn","siebzehn","achtzehn","neunzehn","zwanzig"]
LookupFrench = ["zero","un","deux","trois","quatre","cinq","six","sept","huit","neuf","dix","onze","douze","treize","quatorze","quinze","seize","dix-sept","dix-huit","dix-neuf","vingt"]

rejected_data = []
valid_data = []

def check_dataset(datarow):
  temp = []
  for text in datarow:
    result = check_for_valid_str(text)
    if (result == -1):
      return False
    else:
      temp.append(result)
  valid_data.append(temp)
  return True

data = [["16", "10", "8", "3", "7"],        
["8", "09", "19", "20", "4"],  

["Sechs", "Acht", "Sechzehn", "Funf", "null"],  

["1", "30", "2", "5", "7"],  

["Vierzehn", "Eins", "zwei", "Neun", "Drei"],  

["six", "neuf", "seize", "zero",""],  

["fourteen", "Eleven", "Forteen", "eight", "Twenty"],  

["Douze", "Onze", "Huit", "Quinze", "Sept"],  

["018", "09", "09", "022", "04"],  

["un", "trois", "quatorze", "dix-huit", "vingt"],  

["Five", "Three", "Nineteen", "Twenty", "zero"],  

["einundzwanzig", "Vierzehn", "Eins", "zwei","Vier"]]

LookupEnglish = ["zero","one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen","twenty"]
LookupGerman = ["null","eins", "zwei", "drei", "vier","funf","sechs", "acht", "neun", "zehn","elf","zwolf","dreizehn","vierzehn","funfzehn","sechzehn","siebzehn","achtzehn","neunzehn","zwanzig"]
LookupFrench = ["zero","un","deux","trois","quatre","cinq","six","sept","huit","neuf","dix","onze","douze","treize","quatorze","quinze","seize","dix-sept","dix-huit","dix-neuf","vingt"]

for data_set in data:
  if(check_dataset(data_set) == False):
    rejected_data.append(data_set)
print ("===========Valid Data=======================")
print_data(valid_data)
print("==========Invalid Data=======================")
print_data(rejected_data)